title = "Anatole"
description = "A other zola theme"
base_url = "https://icetigergeo.com"
compile_sass = true
highlight_code = true
build_search_index = false
generate_feed = true
highlight_theme = "base16-ocean-light"
output_dir = "docs"
theme = "anatole-zola"

default_language = "en"

taxonomies = [
    {name = "tags"},
]

[languages.en.translations]
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
date_format = "%Y-%m-%d"
next_page = "Next Page"
last_page = "Last Page"

[extra.social]
github = "Icetigergeo"
twitter = "icetigergeo"
instagram = "geosartshop"
linkedin = "geo-bean-62b57b239"


[extra.show]
tags = false
links = false

